[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'gregsexton/gitv'

[[plugins]]
repo = 'terryma/vim-multiple-cursors'
